{
 "title": "AUTH SERVICE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "P50 P95 P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_requests_duration_seconds_bucket{endpoint!=\"unknown\"}[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}} P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_requests_duration_seconds_bucket{endpoint!=\"unknown\"}[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_requests_duration_seconds_bucket{endpoint!=\"unknown\"}[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}} P99"
    }
   ]
  },
  {
   "title": "HTTP REQUEST TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{endpoint!=\"/metrics\"}",
     "legendFormat": "{{ endpoint }} {{ status }}"
    }
   ]
  },
  {
   "title": "HTTP REQUESTS DURATION",
   "type": "timeseries",
   "description": "Duration of HTTP requests in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_duration_seconds_sum{endpoint!=\"/metrics\"}[5m]) / rate(http_requests_duration_seconds_count{endpoint!=\"/metrics\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}