services:
  auth-service:
    build: .
    depends_on:
      - postgres-dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      AUTH_PORT: ${AUTH_PORT}
    networks:
      - backend
    ports:
      - "${AUTH_PORT:-8080}:${AUTH_PORT:-8080}"

  postgres-dev:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  
    networks:
      - backend
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge
