global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alertrules.yml
  - /etc/prometheus/recording_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alert-manager:9093"]

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8080"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]